server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: auth-service
          uri: lb://AUTH_SERVICE_3
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://USER_SERVICE_4
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: lb://ORDER_SERVICE_5
          predicates:
            - Path=/api/orders/**
