server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # Strongly recommended when using discovery locator
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: lb://ORDER_SERVICE
          predicates:
            - Path=/api/orders/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: gateway
